### ISSUE TITLE
Gulp build doesn't move vendor assets

### ISSUE THREAD

**Issue by jordanbarhorst** [klapec/bourbonify-jekyll#15]
Hey! I'm a huge fan! I noticed that in my latest build, gulp build no longer moves the items under app/bower_components to the vendors folder. Not sure if this is something I'm doing wrong or an actual issue. Thanks for the hard work!

**Comment by klapec** [comment]
Hi. Thanks for your kind words :) This project is quite old now, I haven't got much time to update and maintain it.

Gulp looks for the`bower_components` directory specifically, not `app/bower_components`. If you have your bower dependencies downloaded into `app/bower_components`, you have to modify the `gulpfile.js` file on the line 61 - https://github.com/klapec/bourbonify-jekyll/blob/master/gulpfile.js#L61.

Feel free to ask if you need anything, more than happy to help!

**Comment by jordanbarhorst** [comment]
Ah, this was exactly what was wrong! Thanks!
